prompts:
  - file://../convert.prompt.txt

providers:
    - id: exec:./run-cgpt.sh
      label: "cgpt:ollama"
      config:
        backend: ollama
        model: llama3.2:1b
    - id: exec:./run-cgpt.sh
      label: "cgpt:anthropic:claude-3-5-sonnet-20240620"
      config:
        backend: anthropic
        model: claude-3-5-sonnet-20240620
    - id: exec:./run-cgpt.sh
      label: "cgpt:anthropic:claude-3-haiku-20240307"
      config:
        backend: anthropic
        model: claude-3-haiku-20240307

tests:
  - description: GSM8K word problem to symbolic template conversion
    vars:
      question:
        - "When Sophie watches her nephew, she gets out a variety of toys for him. The bag of building blocks has 31 blocks in it. The bin of stuffed animals has 8 stuffed animals inside. The tower of stacking rings has 9 multicolored rings on it. Sophie recently bought a tube of bouncy balls, bringing her total number of toys for her nephew up to 62. How many bouncy balls came in the tube?"
        - "Percius has a collection of marbles. 40% of them are clear. 20% are black, and the remainder are all the other colors. A friend of his asks if he can take five marbles. On average, how many marbles of other colors will his friend end up getting?"
      answer:
        - |-
          Let T be the number of bouncy balls in the tube.
          After buying the tube of balls, Sophie has 31 + 8 + 9 + T = 48 + T = 62 toys for her nephew.
          Thus, T = 62 - 48 = <<62-48=14>>14 bouncy balls came in the tube.
          #### 14
        - |-
          40% of the marbles are of other colors because 100 - 20 - 40 = <<100-20-40=40>>40
          The friend will on average get 2 other colored marbles because 5 x .4 = <<5*.4=2>>2
          #### 2
    assert:
      - type: contains
        value: "<symbolic_template_question>"
      - type: contains
        value: "<symbolic_template_answer>"
      - type: contains
        value: "#variables:"
      - type: contains
        value: "#conditions:"
      - type: contains
        value: "### {ans}"
      - type: javascript
        value: |
          const hasQuestionTemplate = output.includes("<symbolic_template_question>") && output.includes("</symbolic_template_question>");
          const hasAnswerTemplate = output.includes("<symbolic_template_answer>") && output.includes("</symbolic_template_answer>");
          const hasPlaceholders = output.includes("{name}") && output.includes("{x}");
          const hasRanges = output.includes("range(") && output.includes("sample(");
          return hasQuestionTemplate && hasAnswerTemplate && hasPlaceholders && hasRanges;
